- name: Установка Apache на Debian
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Включение Apache и его добавление в автозагрузку на Debian
  systemd:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
  ignore_errors: yes


- name: Установка Apache на CentOS
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Включение Apache и его добавление в автозагрузку на CentOS
  systemd:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
  ignore_errors: yes
