#!/bin/bash

docker network inspect ci-cd-network >/dev/null 2>&1 || docker network create ci-cd-network

cd docker-registry || exit 1
docker-compose up -d || exit 1

cd ../gitlab-server || exit 1
docker-compose up -d || exit 1

cd ../gitlab-runner || exit 1
docker-compose up -d || exit 1

sleep 10

docker ps
