version: "2.4"

services:
  nginx:
    image: front-nginx
    build:
      context: nginx
    hostname: front-nginx
    restart: unless-stopped
    ports:
      - ${API_PORT}:80
    environment:
      API_PORT: ${API_PORT}
    depends_on:
      - upstream-debian
      - upstream-almalinux

  upstream-debian:
    image: upstream-debian # обновила название для ясности
    build:
      context: debian
    hostname: upstream-debian # обновила название для ясности
    restart: unless-stopped
    volumes:
      - ./hello_apache_page:/var/www/html

  upstream-almalinux:
    image: upstream-almalinux
    build:
       context: almalinux
    hostname: upstream-almalinux
    restart: unless-stopped
    volumes:
      - ./hello_apache_page:/var/www/html
