- name: Обновление пакетов на Debian
  apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"

- name: Установка Nginx на Debian
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Включение Nginx и его добавление в автозагрузку на Debian
  systemd:
    name: nginx
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Обновление пакетов на CentOS
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Установка Nginx на CentOS
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Включение Nginx и его добавление в автозагрузку на CentOS
  systemd:
    name: nginx
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
